# Generated by Django 5.0.3 on 2024-03-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0004_internationalization_batchseed_batchspecies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchsupportedspecies',
            name='quantity',
        ),
        migrations.AddField(
            model_name='batchspecies',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
