version: '3.3'
services:
  mysql:
    image: mysql:8
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: canopeum_db
      MYSQL_ROOT_PASSWORD: canopeum
    ports:
      # Map the port to a non-default SQL port
      - 3308:3306
    volumes:
      - mysql8-data:/var/lib/mysql
      - mysql8-conf:/etc/mysql/conf.d
volumes:
  mysql8-data:
    driver: local
  mysql8-conf:
    driver: local
