[project]
name = "Canopeum"
version = "0.0.0"
requires-python = ">= 3.12"
dependencies = [
  "Django>=5.0.8",
  # Fix for https://github.com/BesLogic/releaf-canopeum/security/dependabot/25
  "dj-database-url",
  "django-cors-headers",
  "djangorestframework-camel-case",
  "djangorestframework-simplejwt",
  # TODO: Bump above 5.3.1 as soon as fixed for https://github.com/BesLogic/releaf-canopeum/security/dependabot/3
  "djangorestframework>=3.15.2",
  # Fix for https://github.com/BesLogic/releaf-canopeum/security/dependabot/15
  "drf-spectacular-sidecar",
  "drf-spectacular>=0.27.2",
  # https://github.com/tfranzel/drf-spectacular/pull/1216
  "googlemaps",
  "mysqlclient",
  "openmeteo-requests>=1.3.0",
  "python-dotenv",
  "requests-cache>=1.2.1",
  "retry-requests>=2.0.0",
]
[project.optional-dependencies]
dev = [
  # Tools
  "mypy", # version taken from [compatible-mypy],
  "pyright>=1.1.374",
  "ruff~=0.7.4",
  # Stubs
  "django-stubs[compatible-mypy]>=5.0.0",
  "djangorestframework-stubs[compatible-mypy]>=3.15.0",
  "types-jsonschema",
]

# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
show_column_numbers = true
implicit_reexport = true
python_version = "3.12"
exclude = [".venv/"]
# https://github.com/typeddjango/django-stubs/issues/579
# https://github.com/typeddjango/django-stubs/issues/1264
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

strict = true
# Implicit return types using pyright ! (mypy doesn't do implicit return types)
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
# Note: mypy still has issues with some boolean infered returns:
# https://github.com/python/mypy/issues/4409
# https://github.com/python/mypy/issues/10149

[[tool.mypy.overrides]]
# Untyped dependencies
module = [
  "djangorestframework_camel_case.*",
  "googlemaps.*",
  "openmeteo_requests.*",
  "rest_framework.*",
  "retry_requests.*",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "canopeum_backend.settings"
