# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
show_column_numbers = true
implicit_reexport = true
python_version = "3.12"
exclude = [".venv/"]
# https://github.com/typeddjango/django-stubs/issues/579
# https://github.com/typeddjango/django-stubs/issues/1264
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

strict = true
# Implicit return types using pyright ! (mypy doesn't do implicit return types)
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
# Note: mypy still has issues with some boolean infered returns:
# https://github.com/python/mypy/issues/4409
# https://github.com/python/mypy/issues/10149

[[tool.mypy.overrides]]
# Untyped dependencies
module = ["djangorestframework_camel_case.*", "rest_framework.*"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "canopeum_backend.settings"
