# Generated by Django 5.1 on 2024-10-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="total_number_seed",
        ),
    ]
