# Generated by Django 5.0.3 on 2024-04-18 19:14

import canopeum_backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.post'),
        ),
        migrations.AlterField(
            model_name='siteadmin',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.site'),
        ),
        migrations.AlterField(
            model_name='siteadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitefollower',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.site'),
        ),
        migrations.AlterField(
            model_name='sitefollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('expires_at', models.DateTimeField(default=canopeum_backend.models.one_week_from_today)),
                ('email', models.EmailField(max_length=254)),
                ('assigned_to_sites', models.ManyToManyField(to='canopeum_backend.site')),
            ],
        ),
    ]
