# Generated by Django 5.1 on 2024-11-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="share_count",
        ),
    ]
