# Generated by Django 5.0.3 on 2024-04-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
