# Generated by Django 5.0.3 on 2024-05-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
