# Generated by Django 5.1 on 2024-10-03 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fertilizertype",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="canopeum_backend.internationalization",
            ),
        ),
        migrations.AlterField(
            model_name="mulchlayertype",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="canopeum_backend.internationalization",
            ),
        ),
        migrations.AlterField(
            model_name="sitetype",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="canopeum_backend.internationalization",
            ),
        ),
        migrations.AlterField(
            model_name="treetype",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="canopeum_backend.internationalization",
            ),
        ),
        migrations.DeleteModel(
            name="FertilizertypeInternationalization",
        ),
        migrations.DeleteModel(
            name="MulchlayertypeInternationalization",
        ),
        migrations.DeleteModel(
            name="SitetypeInternationalization",
        ),
        migrations.DeleteModel(
            name="TreespeciestypeInternationalization",
        ),
    ]
