# Generated by Django 5.1 on 2024-10-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("User", "User"),
                    ("ForestSteward", "Foreststeward"),
                    ("MegaAdmin", "Megaadmin"),
                ],
                max_length=13,
            ),
        ),
    ]
