# Generated by Django 5.0.3 on 2024-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
