# Generated by Django 5.0.3 on 2024-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
    ]
