# Generated by Django 5.1 on 2024-11-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0002_alter_role_name"),
        ("canopeum_backend", "0002_remove_batch_total_number_seed"),
    ]

    operations = []
