# Generated by Django 5.1 on 2024-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0002_batch_image_batch_plant_count_batch_replace_count_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='batchfertilizer',
            constraint=models.UniqueConstraint(fields=('batch', 'fertilizer_type'), name='unique_fertilizer_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='batchmulchlayer',
            constraint=models.UniqueConstraint(fields=('batch', 'mulch_layer_type'), name='unique_mulch_layer_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='batchseed',
            constraint=models.UniqueConstraint(fields=('batch', 'tree_type'), name='unique_seed_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='batchspecies',
            constraint=models.UniqueConstraint(fields=('batch', 'tree_type'), name='unique_species_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='batchsupportedspecies',
            constraint=models.UniqueConstraint(fields=('batch', 'tree_type'), name='unique_supported_species_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='sitetreespecies',
            constraint=models.UniqueConstraint(fields=('site', 'tree_type'), name='unique_tree_species_per_site'),
        ),
    ]
