# Generated by Django 5.1 on 2025-05-17 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canopeum_backend", "0003_update_input_fields_char_limits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="image",
        ),
        migrations.CreateModel(
            name="BatchAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="canopeum_backend.asset",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canopeum_backend.batch",
                    ),
                ),
            ],
            bases=("canopeum_backend.asset",),
        ),
    ]
