# Generated by Django 5.0.3 on 2024-04-12 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0003_make_comment_fields_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(blank=True, through='canopeum_backend.PostAsset', to='canopeum_backend.asset'),
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.site'),
        ),
    ]
