# Generated by Django 5.1 on 2025-04-10 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0003_update_input_fields_char_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='image',
        ),
        migrations.CreateModel(
            name='BatchAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.asset')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batch')),
            ],
        ),
    ]
