# Generated by Django 5.1 on 2024-09-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0003_unique_constraints_for_batch_and_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
