# Generated by Django 5.0.3 on 2024-04-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0003_make_comment_fields_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('MegaAdmin', 'Megaadmin')], default='User', max_length=9),
        ),
    ]
