# Generated by Django 5.1 on 2024-09-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0004_remove_setting_blank_with_date_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.asset')),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batchsponsor'),
        ),
    ]
