# Generated by Django 5.1 on 2024-09-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0004_remove_setting_blank_with_date_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfertilizer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batch'),
        ),
        migrations.AlterField(
            model_name='batchfertilizer',
            name='fertilizer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.fertilizertype'),
        ),
        migrations.AlterField(
            model_name='batchmulchlayer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batch'),
        ),
        migrations.AlterField(
            model_name='batchmulchlayer',
            name='mulch_layer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.mulchlayertype'),
        ),
        migrations.AlterField(
            model_name='batchseed',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batch'),
        ),
        migrations.AlterField(
            model_name='batchseed',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batchseed',
            name='tree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.treetype'),
        ),
        migrations.AlterField(
            model_name='batchspecies',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batch'),
        ),
        migrations.AlterField(
            model_name='batchspecies',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batchspecies',
            name='tree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.treetype'),
        ),
        migrations.AlterField(
            model_name='batchsupportedspecies',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.batch'),
        ),
        migrations.AlterField(
            model_name='batchsupportedspecies',
            name='tree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.treetype'),
        ),
    ]
