# Generated by Django 5.2 on 2025-04-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0004_remove_batch_image_batchasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.asset'),
        ),
    ]
