# Generated by Django 5.1 on 2024-09-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0005_made_batch_join_tables_properties_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canopeum_backend.site'),
        ),
    ]
