# Generated by Django 5.0.3 on 2024-03-24 01:12

import canopeum_backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0006_asset_remove_siteimage_image_remove_postimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=models.FileField(upload_to=canopeum_backend.models.upload_to),
        ),
        migrations.DeleteModel(
            name='SiteAsset',
        ),
    ]
