# Generated by Django 5.0.3 on 2024-04-17 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0006_make_post_created_at_auto_on_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='Body'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('User', 'User'), ('SiteManager', 'Sitemanager'), ('MegaAdmin', 'Megaadmin')], default='User', max_length=11),
        ),
        migrations.AlterField(
            model_name='siteadmin',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteadmin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
