# Generated by Django 5.0.3 on 2024-04-17 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0007_remove_admin_option_in_role_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadmin',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='canopeum_backend.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteadmin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
