# Generated by Django 5.0.3 on 2024-03-24 02:45

import canopeum_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0008_alter_asset_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=models.FileField(upload_to=canopeum_backend.models.upload_to),
        ),
    ]
