# Generated by Django 5.0.3 on 2024-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopeum_backend', '0009_alter_asset_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='linkedin_link',
            new_name='linkedIn_link',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(through='canopeum_backend.PostAsset', to='canopeum_backend.asset'),
        ),
    ]
