name: canopeum_frontend_deploy

on:
  push:
    branches:
      - main
    paths:
      - "canopeum_frontend/**"
      - ".github/workflows/canopeum_frontend_deploy.yml"
  pull_request:
    branches:
      - main
    paths:
      - "canopeum_frontend/**"
      - ".github/workflows/canopeum_frontend_deploy.yml"

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: canopeum_frontend
    steps:
      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - name: Publish Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: ./canopeum_frontend/Dockerfile
          push: true
          tags: ghcr.io/beslogic/canopeum_frontend:latest
          labels: latest
      - run: docker build -t canopeum_frontend .
