name: canopeum_backend_deploy

on:
  push:
    branches:
      - main
    paths:
      - "canopeum_backend/**"
      - ".github/workflows/canopeum_backend_deploy.yml"
  pull_request:
    branches:
      - main
    paths:
      - "canopeum_backend/**"
      - ".github/workflows/canopeum_backend_deploy.yml"

jobs:
  Build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: canopeum_backend
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: 'login'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: ./canopeum_backend
          file: canopeum_backend/Dockerfile
          push: true
          tags: ghcr.io/beslogic/canopeum_backend:latest
          labels: latest
