name: PR Autofixes

on:
  pull_request:
    branches:
      - main

jobs:
  Autofixes:
    runs-on: unbuntu-latest
    # Only run autofixes on PRs
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          # Token with Contents permissions to allow retriggering workflow
          token: ${{ secrets.PR_AUTOFIX_PAT }}

      # Ruff autofixes
      - run: cd canopeum_backend
      - uses: astral-sh/ruff-action@v1
        # Fix even on other steps failure
        if: ${{ !cancelled() }}
        with:
          args: check --fix
      - uses: astral-sh/ruff-action@v1
        # Format even on lint failure
        if: ${{ !cancelled() }}
        with:
          args: format

      # ESLint & Dprint autofixes
      - run: cd ../canopeum_frontend
      - run: npm run lint:fix
        # Fix even on other steps failure
        if: ${{ !cancelled() }}

      - name: Commit autofixes
        uses: EndBug/add-and-commit@v9
        # TODO: Prevent infinite loops, github.event.head_commit.author.name is not accessible in this context
        # if: ${{ github.event.head_commit.author.name != 'github-actions' }}
        # Push autofixes even on failure
        if: ${{ !cancelled() }}
        with:
          default_author: github_actions
